// get map county
export const GET_MAP_COUNTY = 'GET_MAP_COUNTY';


export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAURANTS_FAIL = "GET_RESTAURANTS_FAIL";

export const FILTER_RESTAURANTS = 'FILTER_RESTAURANTS';


export const GET_MAP_LOADER = 'GET_MAP_LOADER';

export const GET_BOROUGH = 'GET_BOROUGH';
export const GET_BOROUGH_SUCCESS = 'GET_BOROUGH_SUCCESS';

export const FILTER_BOROUGH = 'FILTER_BOROUGH';
